In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('IMDB Dataset.csv')

In [5]:
df.sample(5)

                                                  review sentiment
33267  Bad, bad, and did I mention bad? Aside from th...  negative
26267  THE ZOMBIE CHRONICLES <br /><br />Aspect ratio...  negative
6058   If there were two parts that the physically to...  positive
35977  Like his early masterpiece "The Elephant Man" ...  positive
17339  Julian Noble (Pierce Brosnan) is a hit-man. Or...  positive

<h1>1. Lower case</h1>

In [8]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [15]:
# here str is used because series not have a lower function so we conver each series to str and so we called the lower()
df['review'] = df['review'].str.lower()

In [17]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

<h1>2. Remove HTML tags</h1>

In [24]:
# To remove a html tags we use a regular expresions

import re
for i in range(len(df)):
    df.iloc[i,0] = re.sub('<.*?>', "", df.iloc[i,0])

In [25]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [28]:
df.iloc[4,0]

'petter mattei\'s "love in the time of money" is a visually stunning film to watch. mr. mattei offers us a vivid portrait about human relations. this is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. this being a variation on the arthur schnitzler\'s play about the same theme, the director transfers the action to the present time new york where all these different characters meet and connect. each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. stylishly, the film has a sophisticated luxurious look. we are taken to see how these people live and the world they live in their own habitat.the only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. a big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.the acting is good under mr. mattei\'s direction. steve buscemi, rosario dawson, carol kane, michael imperioli, adrian grenier, and the rest of the talented cast, make these characters come alive.we wish mr. mattei good luck and await anxiously for his next work.'

<h1>3. Remove Urls</h1>

In [29]:
text = "go to https://google.com and https://youtube.com"

In [34]:
# This helps to remvoe the urls

re.sub(r'http\S+', "", text)

'go to  and '

In [37]:
text2 = "visit www.google.com today"
re.sub(r'www\S+', "", text2)

'visit  today'

In [39]:
# Combination of both
tex = "go to https://google.com and https://youtube.com visit www.google.com today"
re.sub(r'http\S+|www\S+', '', tex)

'go to  and  visit  today'

<h1>4.  Remove Punctuation</h1>

In [40]:
import string

In [41]:
# with re (regular expresion) also we can remove the punctuation's 

pun = string.punctuation

In [42]:
pun

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [52]:
# r'''[!"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~]'''    ### only this will work 
text = "Hello! How are you? $100 #great @user"
re.sub(r'''[!"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~]''', '', text)

'Hello How are you 100 great user'

In [57]:
""" or you can use a pun """
text = "Hello! How are you? $100 #great @user"

def remove_punc(df):
    for j in range(len(df)):
        for i in pun:
            df.iloc[j,0] = df.iloc[j,0].replace(i,"")

In [58]:
remove_punc(df)

In [59]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [60]:
# these are the 2 methods that we can use 
# to save time we have to  use this 18 times faster than remove_punc

def remove_punctuation(text):
    return text.translate(str.maketrans("","", pun))

In [62]:
import time
st = time.time()
df['review'].apply(remove_punctuation)
print(time.time() - st)

0.7942636013031006

In [63]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

<h1>5. Chat word tratement</h1>

In [64]:
# for this make a dictanary then apply that function to a data

In [65]:
text = "i luv dis movie bt it ws too lng omg!!!"

In [66]:
# we git this in git 
chat_words = {
    "luv"  : "love",
    "dis"  : "this",
    "bt"   : "but",
    "ws"   : "was",
    "lng"  : "long",
    "omg"  : "oh my god",
    "lol"  : "laughing out loud",
    "brb"  : "be right back",
    "idk"  : "i don't know",
    "imo"  : "in my opinion",
    "tbh"  : "to be honest",
    "ngl"  : "not gonna lie",
    "u"    : "you",
    "r"    : "are",
    "ur"   : "your",
    "cant" : "cannot",
    "wont" : "will not",
    "gr8"  : "great",
    "b4"   : "before",
    "2"    : "to",
    "4"    : "for",
}

In [67]:
def treat_chat_words(text):
    words = text.lower().split()                       
    cleaned = [chat_words.get(w, w) for w in words]    
    return ' '.join(cleaned)                            

text = "omg i luv dis movie bt it ws 2 lng"
treat_chat_words(text)

'oh my god i love this movie but it was to long'

<h1>6. Spelling Correction</h1>

In [4]:
pip install indexer

Collecting indexer
  Using cached indexer-0.6.2.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/home/lalithrajr/.local/share/pipx/shared/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/lalithrajr/.local/share/pipx/shared/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lalithrajr/.local/share/pipx/shared/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-iap5je23/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iap5je23/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-iap5je23/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-iap5je23/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 107
          except OSError, ex:
                 ^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: /home/lalithrajr/.local/share/pipx/venvs/jupyterlab/bin/python -m pip install --upgrade pip
ERROR: Failed to build 'indexer' when getting requirements to build wheel
Note: you may need to restart the kernel to use updated packages.

In [1]:
from spellchecker import SpellChecker

spell = SpellChecker()

def correct_spellings(text):
    words = text.split()
    corrected = [spell.correction(w) for w in words]
    return ' '.join(corrected)

text = "I luv thiss moviee it was amazng"
correct_spellings(text)

ModuleNotFoundError: No module named 'indexer'

<h1> 7. Remove Stop words</h1>

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word not in stop_words:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [ ]:
df['review'] = df['review'].apply(remove_stopwords)